# This is a basic workflow to help you get started with Actions

name: task_70

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Current directory
        run: 'pwd'
      
      # Install Java and Maven using action
      - name: Java JDK 17 and Maven setup
        uses: actions/setup-java@v4
        with: 
          java-version: '17'
          distribution: 'zulu'
          cache: 'maven'
          cache-dependency-path: './pom.xml' # optional
      
      #Verify Java Version
      - name: Java Version
        run: 'java -version'
      
      #Verify Maven Version
      - name: Maven version
        run: 'mvn -version'
      
      #Build project
      - name: Build Project with Maven
        run: 'mvn package -DskipTests --file pom.xml'
      
      #Run tests
      - name: Run tests
        run: 'mvn test'
